### ISSUE TITLE
index_hmd_accessory_inclusion_zone missing sensor zone

### ISSUE THREAD

**Issue by TooManyPillows** [ValveSoftware/IndexHardware#2]
index_hmd_accessory_inclusion_zone.stp doesn't take into account the front, right, upper sensor on the Valve index headset. I've circled this sensor with green in the attached image 1.jpg.

Because of this, the index_hmd_accessory_inclusion_zone.stp is missing a zone which is outlined with red in the attached image 2.jpg.

![1](https://user-images.githubusercontent.com/55477101/65115844-410a9a80-d9b6-11e9-96bf-0840f75bfeb0.jpg)
![2](https://user-images.githubusercontent.com/55477101/65115845-410a9a80-d9b6-11e9-9bf8-469642109aee.JPG)

**Comment by vanweric** [comment]
Thanks for the heads up!  We've uploaded an updated stp.  Solidworks is having difficulty reading the resulting file, so we've added an STL as well to that zip.
